ExperimentConfig:
  #Device (cpu, cuda:n) of the host the experiment should use.
  host_device: "cuda:0" 

  #The search trials the HW-NAS should do at max. 
  max_search_trials: 2

  #The number of top models to be tested on the target device.
  top_k: 2

ConnectionConfig:
  target_host: "transfair.local"
  target_user: "robin"

ModelConfig:
  model_type: "MLP"
