FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y git python3 python3-venv python3-pip && \
    apt-get update && apt-get install -y docker.io  && \
    apt-get update && apt-get install -y xxd  && \
    apt-get update && apt-get install -y docker-buildx
WORKDIR /elastic-ai.explorer

# Create venv
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install uv inside venv
RUN pip install uv

COPY . .

RUN uv sync --all-groups
CMD ["sleep", "infinity"]