# The DeploymentConfig gives the necessary information to connect to the target-device.
# If parameters are not specified inside the config, they are set to default values.
DeploymentConfig:
  # The Hostname of target device.
  target_name: "<host>"

  # The Username/user-account of the target device to connect to.
  target_user: "<user>"

  # Select one of the supported hardware platforms: "rpi4", "rpi5". Optional. Defaults to "rpi5".
  target_platform_name: <platform_name>

  # The path (on host) to additional pre-compiled libraries neccessary for execution on target. If docker is used for deployment,
  # It needs to be in the docker build-context. Path can be relative to build-context.
  # Optional. Defaults to "./code/libtorch".
  compiled_library_path: "<path/to/library>"

  # Tag of Crosscompiler Image
  compiler_tag: "cross"

  # Full path to Crosscompiler Docker Image
  path_to_dockerfile: "<path-to-project>/docker/Dockerfile.picross"

  # Full path to docker buildcontext
  build_context: "<path-to-project>/docker"
