FROM debian


ADD  ./code/libtorch /code/libtorch
ADD ./bin/measure_latency /bin
ADD ./code/model_0.pt model_0.pt
ENV LIB_ARCH=arm64

RUN dpkg --add-architecture $LIB_ARCH
RUN apt-get update && \
  apt-get install  --no-install-recommends -y libnuma-dev:$LIB_ARCH\
  libopenblas-dev:$LIB_ARCH \
    libopenmpi-dev:$LIB_ARCH


ENTRYPOINT [ "measure_latency", "model_0.pt"]



