ARG BASE_IMAGE=picobase
FROM ${BASE_IMAGE}:latest AS builder

WORKDIR /code
ARG PATH_TO_SOURCE
ARG SOURCE_NAME
ARG CROSS_COMPILER_PATH

COPY $PATH_TO_SOURCE/ /code/${SOURCE_NAME}/
COPY $CROSS_COMPILER_PATH/data /code/data

RUN mkdir -p /code/build && mkdir -p $BIN_DIR
WORKDIR /code/build

RUN cmake -DPICO_SDK_PATH=$PICO_SDK_PATH ..
RUN make -j$(nproc)
RUN cp ./${SOURCE_NAME}/${SOURCE_NAME}.uf2 $BIN_DIR/

FROM scratch
COPY --from=builder /tmp/bin /
