
##ExperimentConfig that mainly changes the HW-Nas Behavior and defines the name of the experiment.
##If parameters are not specified here, they are set to default values.
ExperimentConfig:
  ##Processor type (cpu, cuda:n) of the host, the experiment should run on.
  host_processor: "cuda:0" 

  ##The search trials the HW-NAS should do at max.
  max_search_trials: 2

  ##The number of top models returned by HW-NAS.
  top_n_models: 2

